import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import Link from "next/link";
import { testAuth } from "@/lib/auth";
import { getUser } from "@/actions/users.actions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // testAuth();
  const user = await getUser();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className={`flex gap-4 p-4`}>
          <Link href={`/tickets`}>tickets list</Link>
          <Link href={`/tickets/new`}>new ticket</Link>
          {!user && <Link href={`/register`}>Register</Link>}
        </nav>
        {children}
        <Toaster position={`bottom-center`} />
      </body>
    </html>
  );
}
